"""stats and user_stats

Revision ID: 2a5907fb4356
Revises: 0001_users_refresh_tokens
Create Date: 2026-05-23 21:49:32.873272

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_stats_user_stats"
down_revision: str | None = "0001_users_refresh_tokens"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stats_key"), "stats", ["key"], unique=True)
    op.create_table(
        "user_stats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stat_id", sa.UUID(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["stat_id"], ["stats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "stat_id", name="uq_user_stat"),
    )
    op.create_index(op.f("ix_user_stats_stat_id"), "user_stats", ["stat_id"], unique=False)
    op.create_index(op.f("ix_user_stats_user_id"), "user_stats", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_stats_user_id"), table_name="user_stats")
    op.drop_index(op.f("ix_user_stats_stat_id"), table_name="user_stats")
    op.drop_table("user_stats")
    op.drop_index(op.f("ix_stats_key"), table_name="stats")
    op.drop_table("stats")
    # ### end Alembic commands ###
