"""activities

Revision ID: ccff9d1953bc
Revises: 0003_seed_stats
Create Date: 2026-05-23 21:52:33.428397

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_activities"
down_revision: str | None = "0003_seed_stats"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column(
            "input_type", sa.Enum("BINARY", "QUANTITY", name="activity_input_type"), nullable=False
        ),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_effects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("stat_id", sa.UUID(), nullable=False),
        sa.Column("xp_change", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["stat_id"], ["stats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["template_id"], ["activity_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("template_id", "stat_id", name="uq_template_stat_effect"),
    )
    op.create_index(
        op.f("ix_activity_effects_stat_id"), "activity_effects", ["stat_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_effects_template_id"), "activity_effects", ["template_id"], unique=False
    )
    op.create_table(
        "activity_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("total_xp_applied", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["template_id"], ["activity_templates.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_logs_created_at"), "activity_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_activity_logs_template_id"), "activity_logs", ["template_id"], unique=False
    )
    op.create_index(op.f("ix_activity_logs_user_id"), "activity_logs", ["user_id"], unique=False)
    op.create_table(
        "activity_log_effects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("stat_id", sa.UUID(), nullable=False),
        sa.Column("xp_applied", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["log_id"], ["activity_logs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["stat_id"], ["stats.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_log_effects_log_id"), "activity_log_effects", ["log_id"], unique=False
    )
    op.create_index(
        op.f("ix_activity_log_effects_stat_id"), "activity_log_effects", ["stat_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activity_log_effects_stat_id"), table_name="activity_log_effects")
    op.drop_index(op.f("ix_activity_log_effects_log_id"), table_name="activity_log_effects")
    op.drop_table("activity_log_effects")
    op.drop_index(op.f("ix_activity_logs_user_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_template_id"), table_name="activity_logs")
    op.drop_index(op.f("ix_activity_logs_created_at"), table_name="activity_logs")
    op.drop_table("activity_logs")
    op.drop_index(op.f("ix_activity_effects_template_id"), table_name="activity_effects")
    op.drop_index(op.f("ix_activity_effects_stat_id"), table_name="activity_effects")
    op.drop_table("activity_effects")
    op.drop_table("activity_templates")
    # ### end Alembic commands ###
